on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.tauron-dystrybucja.pl/iapi/outage/GetOutages?gaid=905894&type=street
          downloaded_filename: outages.json
